# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - # Generic file formatting (not python-specific)
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - # Sorted imports
    repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - # Format code
    repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - # Static analysis
    repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        # See: https://github.com/pre-commit/pre-commit-hooks/issues/112
        args: ["--config=.flake8"]
        exclude: doc
  - # Type hinting/checking
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: [types-mock, types-PyYAML, pelican, pytest, pyquery]
